Task-3.1
m0rphed/SPBU-homework-sem02 pull request #2
Opened 2019-04-05 20:22 UTC by m0rphed

Added Task-3.1: tests for the calculator from Task-2.3 😀

2019-04-08 10:46 UTC, yurii-litvinov requested changes

2019-04-08 10:46 UTC, yurii-litvinov commented on Source/ProblemSet03/Task-3.1/Task-3.1.Tests/CalculatorTests.cs
> +            var c = new Calculator(new StackFromArray<string>(100));
Копипастище. Есть [SetUp]

2019-04-08 10:46 UTC, yurii-litvinov commented on Source/ProblemSet03/Task-3.1/Task-3.1.Tests/CalculatorTests.cs
> +            var r = c.Evaluate("2 2 +");
Такие имена нельзя давать переменным. Буквы пока бесплатны

2019-04-08 10:46 UTC, yurii-litvinov commented on Source/ProblemSet03/Task-3.1/Task-3.1.Tests/CalculatorTests.cs
> +            Assert.AreEqual(4.0, r);
Сравнивать вещественные числа без дельты нельзя. Первый семестр раззачту :)

2019-04-08 10:46 UTC, yurii-litvinov commented on Source/ProblemSet03/Task-3.1/Task-3.1.Tests/StackFromListTests.cs
> +}
Тесты на два разных стека в принципе должны быть одинаковыми, потому что стеки должны работать одинаково. Предлагается как-то воспользоваться https://github.com/nunit/docs/wiki/TestFixtureData, чтобы унифицировать тесты.

2019-04-11 09:02 UTC, yurii-litvinov requested changes

2019-04-11 09:02 UTC, yurii-litvinov commented on Source/ProblemSet03/Task-3.1/Task-3.1.Tests/CalculatorTests.cs
> +        public static Func<IStack<string>> buildFromList = () => new StackFromList<string>();
Зачем они public?

2019-04-11 09:02 UTC, yurii-litvinov commented on Source/ProblemSet03/Task-3.1/Task-3.1.Tests/CalculatorTests.cs
> +            }
Можно через `=>`

2019-04-11 09:02 UTC, yurii-litvinov commented on Source/ProblemSet03/Task-3.1/Task-3.1.Tests/CalculatorTests.cs
> +        }
И оно, мне кажется, не по делу public и не через `=>`

2019-04-11 09:02 UTC, yurii-litvinov commented on Source/ProblemSet03/Task-3.1/Task-3.1.Tests/StackFromListTests.cs
> +            _sut = new StackFromArray<int>(100);
Что-то пошло не так

2019-04-11 11:22 UTC, m0rphed reviewed
Научите меня code review 📝 пожалуйста, конкретно где почитать как настроить Codacy для домашек

2019-04-11 11:22 UTC, m0rphed commented on Source/ProblemSet03/Task-3.1/Task-3.1.Tests/StackFromListTests.cs
> +            _sut = new StackFromArray<int>(100);
```cs
private StackFromList<int> _sut;

[SetUp]
public void Initialize()
{
   // Имеется в виду, что раз это тесты для StackFromList они не должны зависеть от StackFromArray ?
    _sut = new StackFromList<int>();
}
```

2019-04-12 07:32 UTC, yurii-litvinov approved these changes

2019-04-12 07:32 UTC, yurii-litvinov commented on Source/ProblemSet03/Task-3.1/Task-3.1.Tests/StackImplementationsTests.cs
> +            new object[] { buildFromArray, "From array" },
Отступов не хватает

2019-04-12 10:34 UTC, m0rphed commented
Теперь всё ок, я закрываю пулл реквест.

2019-04-12 10:34 UTC, merged