Task-2.1
m0rphed/SPBU-homework-sem02 pull request #3
Opened 2019-04-06 22:16 UTC by m0rphed

Added Task-2.1: Linked List implementation with a few unit tests

2019-04-08 09:29 UTC, yurii-litvinov requested changes
В целом всё правильно, но есть несколько небольших замечаний, которые всё-таки надо поправить

2019-04-08 09:29 UTC, yurii-litvinov commented on Source/ProblemSet02/Task-2.1/Task-2.1.Tests/LinkedListTests.cs
> +            int length = 10;
const, она же известна во время компиляции

2019-04-08 09:29 UTC, yurii-litvinov commented on Source/ProblemSet02/Task-2.1/Task-2.1/IndexOutOfRangeException.cs
> +    public class IndexOutOfRangeException : ApplicationException
Велосипед же: https://docs.microsoft.com/ru-ru/dotnet/api/system.indexoutofrangeexception?view=netframework-4.7.2

2019-04-08 09:29 UTC, yurii-litvinov commented on Source/ProblemSet02/Task-2.1/Task-2.1/LinkedList.cs
> +        /// Indecies starts from zero
Indexes?

2019-04-08 09:29 UTC, yurii-litvinov commented on Source/ProblemSet02/Task-2.1/Task-2.1/LinkedList.cs
> +                throw new IndexOutOfRangeException("Incorrect position");
Кажется, это исключение нигде не бросается с другим сообщением, что вызывает вопросы о полезности сообщения для понимания причины ошибки. Имело бы смысл либо выставлять Message в уонструкторе исключения, либо не заполнять Message вообще (ведь по типу исключения сразу понятно, что произошло).

2019-04-08 09:29 UTC, yurii-litvinov commented on Source/ProblemSet02/Task-2.1/Task-2.1/LinkedList.cs
> +        public void RsetValueOnPosition(int value, int position)
Rset? Это Set или Reset? :)

2019-04-08 09:29 UTC, yurii-litvinov commented on Source/ProblemSet02/Task-2.1/Task-2.1/LinkedList.cs
> +            }
Поиск элемента в заданной позиции встречается повсеместно, а есть принцип Don't Repeat Yourself.

2019-04-10 21:23 UTC, m0rphed commented on Source/ProblemSet02/Task-2.1/Task-2.1/LinkedList.cs
> +        /// Indecies starts from zero
Both "indexes" and "indices" are acceptable plural forms of the word "index"
Вот только у меня получился гибрид 😕

2019-04-11 08:29 UTC, yurii-litvinov approved these changes
Всё отлично, зачтена

2019-04-11 08:29 UTC, yurii-litvinov commented on Source/ProblemSet02/Task-2.1/Task-2.1/EmptyListException.cs
> +        // Throws with custom message (could be specified)
Вполне можно это сделать комментарием XML Documentation

2019-04-11 08:29 UTC, yurii-litvinov commented on Source/ProblemSet02/Task-2.1/Task-2.1.Tests/LinkedListTests.cs
> +            var sut = new LinkedList();
Ещё есть [SetUp], чтобы в каждом тесте не писать одно и то же

2019-04-11 10:48 UTC, m0rphed commented
Тесты проходят, билд жив, всё ок, я закрываю пулл реквест.

2019-04-11 10:49 UTC, merged